name: cppdev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cmake
  - ninja
  - make
  - clangxx
  - doxygen
  - pip
  - pkg-config
  - gnuplot==5.2
  - fftw
  - pip:
    - breathe
    - sphinx
